### ISSUE TITLE
How was format.xml created/generated/obtained?

### ISSUE THREAD

**Issue by krisnadhi** [ec-geolink/design#21]
How was https://github.com/ec-geolink/design/blob/master/voc/dataone/format.xml originally created? Was it manually created?

**Comment by robertarko** [comment]
I scraped the dataone.org page and ran a script to create the OWL file.  Not fancy. :)

**Comment by mbjones** [comment]
The vocabulary is maintained in xml format here:

https://cn.dataone.org/cn/v1/formats

Matt

**Comment by krisnadhi** [comment]
Thanks for the info, Matt, Bob!

**Comment by amoeba** [comment]
In the time since this Issue was closed, the way format.xml is being generated has changed. The big change is that individual formats (e.g. EML 2.0) are not Classes but instead are Resources of class glview:Format.

The script that generates the new formats.xml file is: https://github.com/ec-geolink/design/blob/master/data/dataone/formats/create-d1-formats-graph.py

And the formats.xml file generated by the above script is here: https://github.com/ec-geolink/design/blob/master/data/dataone/formats/formats.xml
