### ISSUE TITLE
dataone: add spatial coverage fields

### ISSUE THREAD

**Issue by mbjones** [ec-geolink/design#29]

**Comment by amoeba** [comment]
I mapped D1's xBoundCoord where x is one of [north, east, south, west] into GL's hasGeometryAsWktLiteral by making a WKT literal POLYGON string .

Not sure if this is the way to go so this issue will stay open.

**Comment by amoeba** [comment]
Updated this today after reading the EML spec about how spatial coverage should be defined in the science metadata. It looks like EML requires all four bounds be entered, even if you only want to express your spatial extent as a point.

The spec then goes on to say that, if you want to express your spatial coverage as a point, simply make the north bound equal the south bound and the west bound equal the east bound. My code checks for this case and inserts a WKT POINT instead of POLYGON.

See 8280ddf59fd5207ae8ed7e2a0c8cf2d509715c89
